package report

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/tt-a1i/tokenmeter/internal/storage"
)

// SessionShareMarkdown builds a compact, social-friendly Markdown summary for a
// single coding-agent session.
func SessionShareMarkdown(s storage.SessionRow, tools []storage.ToolStatRow, files []storage.FileChangeRow, generatedAt time.Time) string {
	var b strings.Builder

	name := sessionName(s)
	fmt.Fprintf(&b, "# TokenMeter Session: %s\n\n", name)
	fmt.Fprintf(&b, "- Platform: %s\n", valueOrDash(s.Platform))
	fmt.Fprintf(&b, "- Model: %s\n", valueOrDash(s.Model))
	fmt.Fprintf(&b, "- Cost: %s\n", formatCost(s.TotalCostUSD))
	fmt.Fprintf(&b, "- Tokens: %s in / %s out / %s total\n",
		formatTokens(s.TotalInputTokens),
		formatTokens(s.TotalOutputTokens),
		formatTokens(s.TotalInputTokens+s.TotalOutputTokens))
	if dur := sessionDuration(s, generatedAt); dur != "" {
		fmt.Fprintf(&b, "- Duration: %s\n", dur)
	}
	if s.CWD != "" {
		fmt.Fprintf(&b, "- Project: %s\n", filepath.Base(s.CWD))
	}
	if s.GitBranch != "" {
		fmt.Fprintf(&b, "- Branch: %s\n", s.GitBranch)
	}
	if s.Tag != "" {
		fmt.Fprintf(&b, "- Tag: %s\n", s.Tag)
	}

	if len(tools) > 0 {
		b.WriteString("\n## Top Tools\n\n")
		for _, t := range topTools(tools, 5) {
			fail := ""
			if t.FailCount > 0 {
				fail = fmt.Sprintf(", %d failed", t.FailCount)
			}
			avg := ""
			if t.AvgMs > 0 {
				avg = fmt.Sprintf(", avg %s", formatDuration(time.Duration(t.AvgMs)*time.Millisecond))
			}
			fmt.Fprintf(&b, "- %s: %d calls%s%s\n", t.ToolName, t.Count, avg, fail)
		}
	}

	if len(files) > 0 {
		creates, edits, deletes := fileChangeCounts(files)
		b.WriteString("\n## File Changes\n\n")
		fmt.Fprintf(&b, "- %d files touched", len(files))
		if creates+edits+deletes > 0 {
			fmt.Fprintf(&b, " (%d created, %d edited, %d deleted)", creates, edits, deletes)
		}
		b.WriteString("\n")
		for _, f := range files[:min(len(files), 5)] {
			fmt.Fprintf(&b, "- %s %s\n", changeSymbol(f.ChangeType), f.FilePath)
		}
		if len(files) > 5 {
			fmt.Fprintf(&b, "- ... %d more\n", len(files)-5)
		}
	}

	fmt.Fprintf(&b, "\n---\nGenerated by TokenMeter at %s\n", generatedAt.UTC().Format("2006-01-02 15:04 UTC"))
	return b.String()
}

func sessionName(s storage.SessionRow) string {
	if s.GitBranch != "" && s.CWD != "" {
		return filepath.Base(s.CWD) + "/" + s.GitBranch
	}
	if s.GitBranch != "" {
		return s.GitBranch
	}
	if s.CWD != "" {
		return filepath.Base(s.CWD)
	}
	if len(s.SessionID) > 12 {
		return s.SessionID[:12]
	}
	return s.SessionID
}

func sessionDuration(s storage.SessionRow, now time.Time) string {
	end := now
	if s.EndTime != nil {
		end = *s.EndTime
	}
	if s.StartTime.IsZero() || end.Before(s.StartTime) {
		return ""
	}
	return formatDuration(end.Sub(s.StartTime))
}

func formatDuration(d time.Duration) string {
	if d < time.Second {
		return d.Round(time.Millisecond).String()
	}
	return d.Round(time.Second).String()
}

func formatCost(cost float64) string {
	if cost >= 1 {
		return fmt.Sprintf("$%.2f", cost)
	}
	return fmt.Sprintf("$%.4f", cost)
}

func formatTokens(n int) string {
	if n >= 1_000_000 {
		return fmt.Sprintf("%.1fM", float64(n)/1_000_000)
	}
	if n >= 1_000 {
		return fmt.Sprintf("%.1fk", float64(n)/1_000)
	}
	return fmt.Sprintf("%d", n)
}

func valueOrDash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}

func topTools(tools []storage.ToolStatRow, limit int) []storage.ToolStatRow {
	out := append([]storage.ToolStatRow(nil), tools...)
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Count == out[j].Count {
			return out[i].ToolName < out[j].ToolName
		}
		return out[i].Count > out[j].Count
	})
	if len(out) > limit {
		out = out[:limit]
	}
	return out
}

func fileChangeCounts(files []storage.FileChangeRow) (int, int, int) {
	creates, edits, deletes := 0, 0, 0
	for _, f := range files {
		switch f.ChangeType {
		case "create":
			creates++
		case "delete":
			deletes++
		default:
			edits++
		}
	}
	return creates, edits, deletes
}

func changeSymbol(changeType string) string {
	switch changeType {
	case "create":
		return "+"
	case "delete":
		return "-"
	default:
		return "~"
	}
}
